<?php
$_helper = $this->helper('catalog/output');
?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
    <div class="category-products">
        <div class="page-title" style="margin: 1em 0; text-align: center;">
            <h2><?php echo $this->__('These Products Are Popular Right Now!') ?></h2>
        </div>
        <ul class="c-list" data-role="listview" data-inset="true">
            <?php foreach ($_products->getItems() as $_product): ?>
                <li data-role="list-divider">
                     <?php
                        if(strlen($_helper->productAttribute($_product, $_product->getName(), 'name')) >= 30)
                            echo substr($_helper->productAttribute($_product, $_product->getName(), 'name'),0,27).'...';
                        else
                            echo $_helper->productAttribute($_product, $_product->getName(), 'name');
                    ?>
                    <span class="ui-li-count"><?php echo Mage::helper('core')->currency($_helper->productAttribute($_product, $_product->getPrice(), 'name')); ?></span>
                </li>
                <li>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                        <div class="wrap">
                            <div class="product-image">
                                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(130); ?>" width="85" height="85" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                            </div>
                            <div class="product-shop">
                                <?php echo substr($_helper->productAttribute($_product, $_product->getShortDescription(), 'name'),0,100).'.....'; ?>
                            </div>
                            <?php if($_product->isSaleable()): ?>
                                <button class="button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>//')"><span><span><span><?php echo $this->__('Add to Cart') ?></span></span></span></button>
                                <div class="clear"></div>
                            <?php else: ?>
                                <p class="availability"><span class="out-of-stock"><?php echo $this->__('Out of stock') ?></span></p>
                                <div class="clear"></div>
                            <?php endif; ?>
                        </div>

                    </a>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
<?php else:?>
    <p class="note-msg"><?php echo $this->__('There are no products.') ?></p>
<?php endif; ?>