<?php 
$_product = $this->getProduct();
$id = $_product->getManufacturer();
?>
<?php if($this->helper('manufacturer')->getManufacturerLink($_product) != ""):?>
<?php if($this->helper('manufacturer')->getShowLogo() || $this->helper('manufacturer')->getShowLink()):?>
<div class="product-brand" style="clear:both">
	<strong><?php echo $this->__("Brand");?></strong>
	<?php echo $this->helper('manufacturer')->getManufacturerLink($_product);?>
</div>
<?php endif;?>
<?php endif;?>